version: 1

update_configs:
  - package_manager: "java:gradle"
    directory: "/core"
    update_schedule: "daily"
  
# Modules
  - package_manager: "java:gradle"
    directory: "/modules/testcontainers"
    update_schedule: "daily"  
  - package_manager: "java:gradle"
    directory: "/modules/liberty"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/modules/payara-micro"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/modules/payara-server"
    update_schedule: "daily"
    
# Test apps
  - package_manager: "java:gradle"
    directory: "/sample-apps/everything-app"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/sample-apps/jaxrs-json"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/sample-apps/jaxrs-mpjwt"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/sample-apps/jdbc-app"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/sample-apps/liberty-app"
    update_schedule: "daily"
  - package_manager: "java:maven"
    directory: "/sample-apps/maven-app"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/sample-apps/payara-app"
    update_schedule: "daily"
  - package_manager: "java:gradle"
    directory: "/sample-apps/wildfly-app"
    update_schedule: "daily"
